spring:
  config:    activate:      on-profile:      - dev
  flyway:    enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mutantsTestDb;
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:      ddl-auto: create
  h2:    console:      enabled: true
      path: /h2-console