spring:
  config:
    activate:
      on-profile:
      - prod
  flyway:
    enabled: true
    locations:    - classpath:db/migration
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWD}
  jpa:
    hibernate:
      ddl-auto: none